title: Gayathree Gopi
theme: jekyll-theme-minimal
logo: /profilepic.jpeg
include: 
  - assets/css/style.css
nav_links:
  - title: Home
    url: /
  - title: About Me
    url: /about/
  - title: Projects
    url: /projects/
